---
abstract: 'Find images within other images'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Remove: 1.42
  Test::File::Cleaner: 0.03
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Imager::Search
name: Imager-Search
no_index:
  directory:
    - inc
    - t
requires:
  File::Slurp: 9999.12
  IO::File: 0
  Imager: 0.65
  Imager::Screenshot: 0.007
  Object::Tiny: 1.06
  Params::Util: 0.33
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
